
spring:
  datasource:
    url: jdbc:mysql://localhost/osxmdb
    username: root
    password: ENC(nq2g0w4T9h2PsS//Srp1xQ==)  #123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #jndi-name: java:jboss/datasources/customers
    
  jpa:
    hibernate:
      ddl-auto: none

jasypt:
  encryptor:
    # algorithm: PBEWithHMACSHA512AndAES_256 # 指定加密算法
    algorithm: PBEWithMD5AndDES
    password: oscar # 指定加密密码（建议使用复杂且安全的字符串）
    iv-generator-classname: org.jasypt.iv.NoIvGenerator