spring:
  application:
    name: my-client-app  # 对应配置文件前缀 client-app-{profile}.yml
  config:
    import: "configserver:"    
  cloud:
    config:
      uri: http://localhost:8888  # Config Server 地址
      profile: dev  # 激活的环境